const styles = {
  Palette: { height: '100vh', overFlow: 'hidden', display: 'flex', flexDirection: 'column' },
  colors: {
    height: '90%',
  },
  goBack: {
    width: '20%',
    margin: '0 auto',
    height: '50%',
    display: 'inline-block',
    position: 'relative',
    cursor: 'pointer',
    marginBottom: '-4px',
    opacity: '1',
    backgroundColor: 'black',
    '& a': {
      width: '100px',
      height: '30px',
      position: 'absolute',
      color: 'white',
      display: 'inline-block',
      top: '50%',
      left: '50%',
      marginLeft: '-50px' /*offset*/,
      marginTop: '-15px',
      textAlign: 'center',
      outline: 'none',
      background: 'rgba(255, 255, 255, 0.3)',
      fontSize: '1rem',
      lineHeight: '30px',
      border: 'none',
      textTransform: 'uppercase',
      textDecoration: 'none',
    },
  },
};
export default styles;
